#os:
#  - linux
#  - osx
dist: bionic
language: csharp
solution: eformSDK.sln
mono: none
services:
- mysql
jobs:
  include:
    - script: ./unit-tests.sh
    - script: ./integration-tests-core.sh
    - script: ./integration-tests-sqlcontroller.sh
    - stage: "Deploy"
      if: branch = master
      script: ./deploy.sh
