#os:
#  - linux
#  - osx
dist: bionic
arch:
  - amd64
language: csharp
solution: eformSDK.sln
mono: none
services:
- mysql
jobs:
  include:
    - stage: "Tests"
      script: ./unit-tests.sh
    - stage: "Integration tests"
      script: ./integration-tests.sh
    - stage: "Deploy"
      script: ./deploy.sh
