dist: bionic
language: csharp
solution: eformSDK.sln
mono: none
dotnet: 3.0.100
services:
- mysql
jobs:
  include:
    - stage: testing
      os: linux
      arch:
        - amd64
      script: ./unit-tests.sh
    - stage: testing
      os: linux
      arch:
        - amd64
      script: ./integration-tests-core.sh
    - stage: testing
      os: linux
      arch:
        - amd64
      script: ./integration-tests-sqlcontroller.sh
    #- stage: testing
    #  os: linux
    #  arch:
    #    - arm64
    #  script: ./unit-tests.sh
    #- stage: testing
    #  os: linux
    #  arch:
    #    - arm64
    #  script: ./integration-tests-core.sh
    #- stage: testing
    #  os: linux
    #  arch:
    #    - arm64
    #  script: ./integration-tests-sqlcontroller.sh
    - stage: "Deploy"
      if: branch = master
      os: linux
      arch: amd64
      script: ./deploy.sh
