dist: xenial
language: csharp
solution: eformSDK.sln
mono: none
dotnet: 2.2
services:
- mysql
script:
  - dotnet restore
  - dotnet build eFormSDK.sln
  - dotnet test -v n eFormSDK.Integration.Tests/eFormSDK.Integration.Tests.csproj
