language: csharp
solution: eFormSDK.sln
before_install:
  - sudo apt-get -qq update
  - wget -q https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get install apt-transport-https
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-2.1
mono:
  - latest

dotnet: 2.1.0
services:
  - mysql
script:
  - dotnet --info
  - dotnet build eFormSDK.sln
  - dotnet test eformSDK.Integration.Tests/bin/Debug/netcoreapp2.1/eFormSDK.Integration.Tests.dll
  - echo "show databases;" | mysql -u travis
#
#matrix:
#  include:
#  - dotnet: 2.1.300
#    mono:
#      - latest
#
#    env: DOTNETCORE=2.1
#    install:
##    - travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./eFormSDK.sln
#    - nuget restore eFormSDK.sln
#    - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
#    script:
##    - msbuild ./eFormSDK.sln
#    - xbuild /p:Configuration=Release eFormSDK.sln
#    - mono ./testrunner/NUnit.Runners.console.2.6.4/tools/nunit.console.exe ./eformSDK.Integration.Tests/bin/Debug/netcoreapp2.1/eFormSDK.Integration.Tests.dll
#    - echo "show databases;" | mysql -u travis
#
