skip_tags: true

image: Visual Studio 2019

shallow_clone: true                 # default is "false"

# enable service required for build/tests
services:
  - mssql2017

before_build:
- appveyor-retry dotnet restore
